### ISSUE TITLE
If the server is started with 2 replicas at the same time, the replicas might not find each other

### ISSUE THREAD

**Issue by nostra** [pires/hazelcast-kubernetes-bootstrapper#12]
The problem is mitigated by starting just 1 replica, and then scaling it up afterwards. 

The reason is that the subset addresses are separated into _addresses_ and _notReadyAddresses_, as seen at http://localhost:8000/api/v1/namespaces/default/endpoints/hazelserver

```
...
  "subsets": [
    {
      "addresses": [
        {
          "ip": "172.17.0.7",
          "nodeName": "minikube",
          "targetRef": {
            "kind": "Pod",
            "namespace": "default",
            "name": "hazelserver-437489592-4fzyl",
            "uid": "b85aa568-b6dc-11e6-8ea7-9644ba674aae",
            "resourceVersion": "142219"
          }
        }
      ],
      "notReadyAddresses": [
        {
          "ip": "172.17.0.4",
          "nodeName": "minikube",
          "targetRef": {
            "kind": "Pod",
            "namespace": "default",
            "name": "hazelserver-437489592-fxsmz",
            "uid": "7d7a72dc-b6dd-11e6-8ea7-9644ba674aae",
            "resourceVersion": "142609"
          }
        }
      ],
...
```

The HazelcastDiscoveryController.java#L120 could be updated to cater for this.

I am sorry not to provide a pull request for this, but I am now using io.fabric8:kubernetes-client instead of doing the call directly. I run minikube with kubernetes 1.4.3. I submit this issue, as I suspect you would like to know about this.

**Comment by pires** [comment]
Thank you, once more @nostra! I understand the appeal of using fabric8 client but I am trying to avoid external dependencies. But if you're using it, I'm open to review a PR that adopts it 👍

**Comment by hotstepper13** [comment]
I ran into the same issue today. My cluster with 3 replicas wasnt starting because of this. My Workaround was to remove (comment out) the readiness probe so the cluster was able to start.

I think this could be solved without external dependency by just merging the addresses with the notReadyAddresses.

Also the is a null check missing because in my case a null pointer exception was thrown because subset.addresses (line 122) was null. The null check was only to subset and since this was not null and not empty it goes ahead.

I could think of a fallback so if subset.addresses is null then observe subset. notReadyAddresses for possible cluster members.

Sure this doesnt feel well because adding notReady member sounds like a bad idea but it should do the trick and allow a fresh cluster to be started.

Just to have it asked:
What happens if the member change over time? If we start with three nodes, their ips will be added as members to the cluster. If one node goes done and a new one comes up, it will most likely get a new ip. Will the new member announce itself to the cluster?

**Comment by nostra** [comment]
@hotstepper13 As for the last question: In my experience, as long as the servers have found each other initially, additions and removals works seamlessly. So the answer is "yes". And the one that went down will be removed.

**Comment by pires** [comment]
> as long as the servers have found each other initially, additions and removals works seamlessly

Correct, because Hazelcast nodes leak the known cluster topology to any newly connected nodes.

@nostra it seems I overlooked the info you provided since, as @hotstepper13 said, it should be enough to add not-yet-ready addresses to the nodes list. I'll be picking this up this week. Ping me next week if I don't deliver.

**Comment by hotstepper13** [comment]
I think the PR should do the trick. As mentioned in the RP, I havent tested this as it would mean to create a full build job (have not set up kube locally) for it and the last time your release was very fast to I think this could be a way to go.

**Comment by pires** [comment]
The PR doesn't do the trick, yet. Unfortunately, I don't have the time to add e2e tests but manual testing is possible, and what I usually do before publishing.

**Comment by hotstepper13** [comment]
@pires Any updates for your schedule?

**Comment by pires** [comment]
Looking at this now.

**Comment by pires** [comment]
There's a chance also that this PR won't work because when there's a lookup for pods running Hazelcast, there might be none scheduled (not even in the not-ready state).

**Comment by pires** [comment]
Merged.
